[Peer]
# Client peer for wg-server.
# Related client file: xray-client/wg-config/wg_confs/wg0.conf
PublicKey = tlzuy6meDZ+9u2NMBDBWAnrwkz/reSm/CSzwYSITazA=
PresharedKey = qkkMdfYjh19n66OHIhhXX2Jpz3qfvEznl6gd4AC9LQg=
AllowedIPs = 10.13.13.2/32
