[Peer]
# Client peer for wg-server.
# Related client file: xray-client/wg-config/wg_confs/wg0.conf
PublicKey = tlzuy6meDZ+9u2NMBDBWAnrwkz/reSm/CSzwYSITazA=
# PSK временно отключен для диагностики handshake.
# После стабилизации можно вернуть одинаковый PresharedKey на обе стороны.
AllowedIPs = 10.13.13.2/32
