services:
  xray:
    # Запускать на сервере в США (45.61.57.127)
    image: teddysun/xray:latest
    container_name: xray-reality-server
    restart: always
    network_mode: "host" # Важно для корректной работы с портами и UDP
    volumes:
      - ./config:/etc/xray
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  wireguard:
    # Запускать на сервере в США (45.61.57.127)
    image: linuxserver/wireguard:latest
    container_name: wg-server
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - SERVERPORT=51820
      - PEERS=1 # Создаст конфиг для одного клиента автоматически
      - ALLOWEDIPS=0.0.0.0/0
      - PERSISTENTKEEPALIVE_PEERS=25
    volumes:
      # Связанные файлы:
      # - проект: xray-server/wg-config/
      # - контейнер: /config/peer1/peer1.conf (публичный ключ клиента для wg-server)
      - ./wg-config:/config
      - /lib/modules:/lib/modules:ro