services:
  xray-client:
    # Запускать на российском сервере (91.188.215.79)
    image: teddysun/xray:latest
    container_name: xray-reality-client
    restart: no
    ports:
      # WireGuard-клиент отправляет UDP трафик в этот порт докодемо-инбаунда Xray
      - "51821:51821/udp"
    volumes:
      - ./config/config.json:/etc/xray/config.json:ro

  wireguard-client:
    # Запускать на российском сервере (91.188.215.79)
    image: linuxserver/wireguard:latest
    container_name: wg-client
    restart: no
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./wg-config/wg_confs/wg0.conf:/config/wg_confs/wg0.conf:ro