services:
  xray-client:
    image: teddysun/xray:latest
    container_name: xray-reality-client
    restart: always
    network_mode: "host"
    volumes:
      - ./config:/etc/xray

  wireguard-client:
    image: linuxserver/wireguard:latest
    container_name: wg-client
    restart: always
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./wg-config:/config