services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy-rf
    environment:
      # РФ endpoint для телефона (сканирование QR в приложении WireGuard)
      - WG_HOST=91.188.215.79

      # Пароль для входа в веб-интерфейс (см. README.md)
      - PASSWORD_HASH=$$2b$$12$$.HhU.E0gUMdnjyMQrQAi/OW0KfLPAm1.XsEsCXJ1xEc94Mq7kGXPC

      # Порт веб-админки c кнопкой генерации QR
      - PORT=51822

      # WireGuard порт для подключения телефона
      - WG_PORT=51823

      # Опционально: DNS для клиентов (например, Google или Cloudflare)
      - WG_DEFAULT_DNS=1.1.1.1,8.8.8.8

      # Настройка подсети для VPN (обычно менять не нужно)
      - WG_DEFAULT_ADDRESS=10.8.0.x
    volumes:
      - ./.wg-easy:/etc/wireguard
    ports:
      - "51823:51823/udp"
      - "51822:51822/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
