[Interface]
# Ключ этого клиента (из peer1.conf сервера)
# Связанный файл в проекте: xray-client/wg-config/wg_confs/wg0.conf
# Связанный runtime-файл на сервере: /config/peer1/peer1.conf (в контейнере wg-server)
PrivateKey = EADcTnZdB14lNkMnoLBS0MFVbbrWmzpJfgx4NuhQmV8=
Address = 10.13.13.2/32

[Peer]
# Публичный ключ интерфейса wg-server (проверка: docker exec -it wg-server wg show)
PublicKey = ZEB5fPu+9Ia+shw6gQ4UOcVDBrTbG9PJ5ZInURh//Qk=
# Ключ PSK (если он был в peer1.conf, если нет — удалите строку)
PresharedKey = qkkMdfYjh19n66OHIhhXX2Jpz3qfvEznl6gd4AC9LQg=
# MTU = 1280
# ОГРАНИЧИВАЕМ МАРШРУТ, чтобы не упал SSH
AllowedIPs = 10.13.13.0/24

# ОТПРАВЛЯЕМ В XRAY-CLIENT (Reality туннель)
# Это внутренний docker DNS-адрес контейнера xray-client на российском сервере
Endpoint = xray-reality-client:51821
# Поддерживаем соединение активным через NAT
PersistentKeepalive = 20